### PR TITLE
Fixed bugs reading QI and QL

### PR DESCRIPTION
**Pull request by yuanjianz**
QI and QL in GEOS-IT processed files are all zero due to wrong reading process. 
Now reading QI and QL from `asm` instead of `cld`.

Changed files: Code/GeosItA3CldModule.F90

### CODE REVIEW

**Comment by lizziel** [comment]
Excellent catch that the asm file was not being read to get QI and QL! I have a general question about QI/QL handling, which is whether we should be handling the same way as GEOS-FP or MERRA2. For GEOS-FP processing, if I am interpreting the code correctly, we derive QI and QL from other met-fields. For MERRA2 we read it from file (3dCldNv, hence the source of the bug for the GEOS-IT code). The question is which is better.

**Comment by msulprizio** [comment]
> I have a general question about QI/QL handling, which is whether we should be handling the same way as GEOS-FP or MERRA2. For GEOS-FP processing, if I am interpreting the code correctly, we derive QI and QL from other met-fields. For MERRA2 we read it from file (3dCldNv, hence the source of the bug for the GEOS-IT code). The question is which is better.

@lizziel I would think it's better to read it directly from file. I'm wondering if maybe that field wasn't available in GEOS-FP (or maybe even back to what the GEOS-Chem community referred to as GEOS-5, GEOS-4, etc.).

Tagging @yantosca for any input.

**Comment by yantosca** [comment]
Hi all, yes, I think the QI & QL should be read if possible instead of being derived.

**Comment by lizziel** [comment]
Since QI and QL are now available for FP do you think we should also update our GEOS-FP processing code to read it directly? More consistency across the 3 processing packages would be great.

**Review by lizziel — APPROVED** [review]
Looks good to merge.

**Pull request merged**
